apiVersion: v1
kind: Secret
metadata:
  name: tg-bot
  namespace: dev-tender-stallman
stringData:
  bot_username: "dev_resto_bot"  # Замените значение на своё
  token: "6490773732:AAHCbP3chgcaT2BWJFipVXvAkIAINcLfIC4"  # Замените значение на своё
  webhook_token: "YPXPdw4L56JhOVlFbmwZGlNLdkuQcWSwHuX7wib"  # Замените значение на своё
